module.exports = {
    apps: [
        {
            name: "dev",
            script: "./dist/app.js",
            env: {
                NODE_ENV: 'development',
            }
        },
        {
            name: "test",
            script: "npm",
            args: "run start",
            env: {
                NODE_ENV: 'production',
            }
        }
    ]
}